CREATE TABLE categories (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  name CHARACTER VARYING NOT NULL,
  slug CHARACTER VARYING NOT NULL
);

CREATE INDEX index_slug ON categories(slug);
