// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Movie struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
}

type NewMovie struct {
	Title string `json:"title"`
}
